### ISSUE TITLE
Re-Listing Ivy Oracle

### ISSUE THREAD

**Issue by ivy-oracle** [TowoLabs/ftso-signal-providers#256]
Dear TowoLabs,

I noticed Ivy Oracle have been de-listed from the Bifrost wallet provider list after the extended requirement is added. However, Ivy Oracle meets all the requirements stated on the new extended requirements. May I ask what was the reason for Ivy Oracle being de-listed?

Happy to get in touch to discuss or ease any concerns you may have if needed. 

Regards,
Ivy Oracle Team

**Comment by RareData** [comment]
- You're unknown to our team and using an anonymous GitHub handle.
- We can't currently assess whether you're using a private node

We've sent you a request to schedule a call.
