### ISSUE TITLE
on-chain address is referenced on the signal provider's website

### ISSUE THREAD

**Issue by mnguyen-io** [TowoLabs/ftso-signal-providers#291]
Hi there, I'm looking to be listed as a signal provider and just had a question regarding:

`The on-chain address is referenced on the signal provider's website (enforced 2023-03-31)`

Is this absolutely necessary? If I'm listed before 2023-03-31 (enforcement date) is this still required? Thank you

**Comment by RareData** [comment]
It'll be enforced from 2023-03-31, for all providers.
