### ISSUE TITLE
Listed property for 1FTSO

### ISSUE THREAD

**Issue by 1FTSO** [TowoLabs/ftso-signal-providers#300]
Hello,
1FSTO fulfill all the extended requirements to have the "listed" property since early January.
If you need any other info to add the listed property, please contact me.

Thanks

**Comment by RareData** [comment]
1FTSO was using our public Songbird cluster to submit and was therefore not eligible for listing.

**Comment by RareData** [comment]
This was checked 15th December 2022. You mean that changed between December and January?

**Comment by 1FTSO** [comment]
Yes, since early January 2023 we submits the prices to our private node for both Songbird and Flare.

**Comment by RareData** [comment]
In the next-branch, planned merge.
