### ISSUE TITLE
Listed property for Fly2Sonic

### ISSUE THREAD

**Issue by fly2sonic** [TowoLabs/ftso-signal-providers#315]
Hi, TowoLabs Team

Our pull request has been successfully merged, but we noticed that the 'listed' property has not been assigned yet.
We've checked out the extended requirements, and it looks like Fly2Sonic meets all of them without a hitch:

We're running only one signal provider on this network, keeping it straightforward and strong.
For added security, we're using a private node to submit prices.
And Fly2Sonic has no legal, development, or operational connections with other signal providers.
The algorithm we use is homegrown, making it transparent and independent.
Our voting power is up to snuff for active participation in the FTSO system.
We've maintained at least 95% uptime over the last 30 days – so we're always available.

We had a chat with Bifrost wallet support, and they mentioned that meeting these requirements should be enough for getting the 'listed' property.

So, we're kindly requesting you to consider adding the 'listed' property to our Fly2Sonic signal provider. We're super excited to see it go live!

Thanks a bunch for your support, and if you need any more info or have any questions, just give us a shout.

Looking forward to your response!

**Comment by fly2sonic** [comment]
Any updates? @RareData

**Comment by RareData** [comment]
Stopped providing prices.
