### ISSUE TITLE
Approved provider not appearing in app

### ISSUE THREAD

**Issue by benry1** [TowoLabs/ftso-signal-providers#35]
Hi - WitterFTSO (PR #31) was merged a few minutes before BeamFTSO (#32) and 4DadsFTSO (#33). However only Beam and 4Dads is showing in the app as a provider. Is there some mistake in the WitterFTSO PR or anything I can do at this point? Thanks!

**Comment by RareData** [comment]
Yes the merge removed the chain ID row, detected and adjusted.
